# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master


variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "10.x"

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
          yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
    displayName: cache yarn packages

  - script: |
      yarn install
    displayName: "yarn install"

  - script: |
      yarn run validate
    displayName: "yarn validate"

  - script: |
      yarn run build
    displayName: "yarn build"

  - script: |
      yarn run deploy:preview
    displayName: "deploy preview"
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

  - script: |
      yarn run deploy:preview
    displayName: "deploy prod"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
